name: Build and publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IPFS_DEPLOY_CLOUDFLARE__API_EMAIL: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_EMAIL }}
      IPFS_DEPLOY_CLOUDFLARE__API_KEY: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_KEY }}
      IPFS_DEPLOY_CLOUDFLARE__ZONE: sanderdijkhuis.nl
      IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.ontology-browser.sanderdijkhuis.nl
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Test and build
        run: |
          npm ci
          npm run build
        env:
          LANG: en_US.UTF-8
          CI: true
      - name: Publish
        run: |
          echo IPFS_DEPLOY_CLOUDFLARE__API_EMAIL=$IPFS_DEPLOY_CLOUDFLARE__API_EMAIL >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__API_KEY=$IPFS_DEPLOY_CLOUDFLARE__API_KEY >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__API_ZONE=$IPFS_DEPLOY_CLOUDFLARE__API_ZONE >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__API_RECORD=$IPFS_DEPLOY_CLOUDFLARE__API_RECORD >> .env
          npx ipfs-deploy -d cloudflare ~/work/ontology-browser/ontology-browser/build
